version: '3'
services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./db:/var/lib/mongo

  backend:
    build:
      context: backend
    ports:
      - "5000:5000"
    environment:
        - MONGO_URI=mongodb://db:27017/lab_requirement_db
        - BACKEND_PORT=5000
        - JWT_KEY=secret
    depends_on:
      - db

  frontend:
    build: 
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
      - frontend/.env.local
    depends_on:
      - backend